# 矩阵(Matrix)

## 矩阵加法

In [1]:
# 载入套件
import numpy as np

# 矩阵
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])

# 加法
print(A + B)

[[7 7 7]
 [7 7 7]]


In [2]:
# 减法
print(A - B)

[[-5 -3 -1]
 [ 1  3  5]]


## 矩阵乘法

In [3]:
# 载入套件
import numpy as np

# 矩阵
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[9,8],
              [7,6],
              [5,4],
             ])

# 乘法
print(A @ B)

[[ 38  32]
 [101  86]]


In [4]:
# 乘法：A x B != B x A

A = np.array([[1,2],
              [4,5]])
B = np.array([[9,8],
              [7,6],
             ])

print(A @ B)
print()
print(B @ A)
print()
print('A x B != B x A')

[[23 20]
 [71 62]]

[[41 58]
 [31 44]]

A x B != B x A


## 转置矩阵

In [5]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

# 转置矩阵
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
# 两次转置，会回复成原来的矩阵
print(A.T.T)

[[1 2 3]
 [4 5 6]]


## 反矩阵

In [8]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             ])
print(np.linalg.inv(A))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [9]:
A.shape

(3, 3)

## A x A反矩阵 = 单位矩阵(I)

In [10]:
# A @ A反矩阵 = 单位矩阵(I)
A = np.array([[9,8],
              [7,6],
             ])

print(np.around(A @ np.linalg.inv(A)))

[[1. 0.]
 [0. 1.]]


In [11]:
# A @ A反矩阵 = 单位矩阵(I)
A = np.array([[1,2,3],
              [4,7,6],
              [7,9,9],
             ])

print(np.around(A @ np.linalg.inv(A)))

[[ 1. -0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [12]:
# A @ A反矩阵 != 单位矩阵(I)
# A 为 singular 矩阵
# 第二行 = 第一行 + 1
# 第三行 = 第一行 + 2
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             ])

print(np.around(A @ np.linalg.inv(A)))

[[ 0.  1. -0.]
 [ 0.  2. -1.]
 [ 0.  3.  2.]]


## ‘内积’或称‘点积乘法’(Dot Product)

In [13]:
# 载入套件
import numpy as np

# 向量(Vector)
v = np.array([2,1])
s = np.array([-3,2])

#‘内积’或称‘点积乘法’(Dot Product)
d = v @ s

print (d)

-4


## 计算夹角 θ

In [14]:
# 载入套件
import math
import numpy as np

# 向量(Vector)
v = np.array([2,1])
s = np.array([-3,2])

# 计算长度(magnitudes)
vMag = np.linalg.norm(v)
sMag = np.linalg.norm(s)

# 计算 cosine(θ)
cos = (v @ s) / (vMag * sMag)

# 计算 θ
theta = math.degrees(math.acos(cos))

print(theta)

119.74488129694222
