# Sequential model

In [1]:
import tensorflow as tf

## 建立模型结构

## 模型语法 1

In [2]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

## 模型语法 2：将input_shape拿掉，以model参数设定

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

x = tf.keras.layers.Input(shape=(28, 28))
# 或 x = tf.Variable(tf.random.truncated_normal([28, 28]))
y = model(x)

## 模型语法 3：可以直接串连神经层

In [4]:
layer1 = tf.keras.layers.Dense(2, activation="relu", name="layer1")
layer2 = tf.keras.layers.Dense(3, activation="relu", name="layer2")
layer3 = tf.keras.layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

## 临时加减神经层

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

# 删减一层
model.pop()
print(f'神经层数: {len(model.layers)}')
model.layers

神经层数: 3


In [6]:
# 增加一层
model.add(tf.keras.layers.Dense(10))
print(f'神经层数: {len(model.layers)}')
model.layers

神经层数: 4


## 取得模型及神经层资讯

In [7]:
# 建立 3 layers
layer1 = tf.keras.layers.Dense(2, activation="relu", name="layer1", 
                               input_shape=(28, 28))
layer2 = tf.keras.layers.Dense(3, activation="relu", name="layer2")
layer3 = tf.keras.layers.Dense(4, name="layer3")

# 建立模型
model = tf.keras.models.Sequential([
  layer1,
  layer2,
  layer3
])

# 读取模型权重
print(f'神经层参数类别总数: {len(model.weights)}')
model.weights

神经层参数类别总数: 6


[<tf.Variable 'layer1/kernel:0' shape=(28, 2) dtype=float32, numpy=
 array([[-0.10640502,  0.3605774 ],
        [-0.08907318, -0.17315978],
        [ 0.1200158 , -0.28237817],
        [ 0.24987322, -0.3639028 ],
        [ 0.15365154,  0.24755305],
        [-0.3127381 ,  0.10788786],
        [ 0.08372974, -0.22560312],
        [ 0.3914864 ,  0.09738165],
        [-0.19479197, -0.01712051],
        [ 0.12762403, -0.26360968],
        [ 0.12762141,  0.2805773 ],
        [ 0.13974649,  0.12249672],
        [ 0.36713785,  0.40628284],
        [ 0.42620873, -0.04030997],
        [ 0.43528122, -0.32735592],
        [ 0.31521922,  0.07268167],
        [ 0.27168196,  0.1796459 ],
        [ 0.22482169,  0.04790714],
        [ 0.25158632,  0.2119981 ],
        [-0.37386125, -0.3107264 ],
        [ 0.3775435 , -0.20909612],
        [-0.13379535,  0.44203997],
        [ 0.05903548,  0.03686729],
        [ 0.0125601 , -0.41514012],
        [-0.36170176,  0.4320925 ],
        [ 0.00438523,  0.2599134

In [8]:
print(f'{layer2.name}: {layer2.weights}')

layer2: [<tf.Variable 'layer2/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.12554866, -0.88298076, -0.7784833 ],
       [-0.2880749 ,  0.4587078 , -0.09641045]], dtype=float32)>, <tf.Variable 'layer2/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]


In [9]:
# 取得模型汇总资讯
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (None, 28, 2)             58        
_________________________________________________________________
layer2 (Dense)               (None, 28, 3)             9         
_________________________________________________________________
layer3 (Dense)               (None, 28, 4)             16        
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


## 一边加神经层，一边显示模型汇总资讯，以利除错

In [10]:
from tensorflow.keras import layers

model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

# 显示目前模型汇总资讯
model.summary()

# The answer was: (40, 40, 32), so we can keep downsampling...

model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

# 显示目前模型汇总资讯
model.summary()

# Now that we have 4x4 feature maps, time to apply global max pooling.
model.add(layers.GlobalMaxPooling2D())

# Finally, we add a classification layer.
model.add(layers.Dense(10))

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 40, 40, 32)        0         
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
____________________________

## 取得每一层神经层的output

In [11]:
# 设定模型
initial_model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

# 设定模型的 input/output
feature_extractor = tf.keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

# 呼叫 feature_extractor 取得 output
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
 array([[[[0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          ...,
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ]],
 
         [[0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.02362364, 0.        , ..., 0.        ,
           0.        , 0.        ],
          ...,
       

In [12]:
# 设定模型
initial_model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

# 设定模型的 input/output
feature_extractor = tf.keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name="my_intermediate_layer").output,
)

# 呼叫 feature_extractor 取得 output
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

<tf.Tensor: shape=(1, 121, 121, 32), dtype=float32, numpy=
array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.38350073],
         ...,
         [0.        , 0.     