# Grid World迷宫之策略评估

In [1]:
# 载入相关套件
import numpy as np
from lib.envs.gridworld import GridworldEnv

In [2]:
# 环境
env = GridworldEnv()

In [3]:
# 策略评估函数
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    # 状态值函数初始化
    V = np.zeros(env.nS)
    while True:
        delta = 0
        # 更新每个状态值的函数
        for s in range(env.nS):
            v = 0
            # 计算每个行动后的状态值函数
            for a, action_prob in enumerate(policy[s]):
                # 取得所有可能的下一状态值
                for  prob, next_state, reward, done in env.P[s][a]:
                    # 状态值函数公式，依照所有可能的下一状态值函数加总 
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
            # 比较更新前后的差值，取最大值
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        # 若最大差值 < 门槛值，则停止评估
        if delta < theta:
            break
    return np.array(V)

In [4]:
# 随机策略，机率均等
random_policy = np.ones([env.nS, env.nA]) / env.nA
# 评估
v = policy_eval(random_policy, env)

In [5]:
print("状态值函数:")
print(v)
print("")

print("4x4 状态值函数:")
print(v.reshape(env.shape))
print("")

状态值函数:
[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569
   0.        ]

5x5 状态值函数:
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]



In [6]:
# 验证答案是否正确
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)